services:
  db:
    image: timescale/timescaledb:latest-pg14
    container_name: banking_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bankTest
    ports:
      - "5432:5432"
    volumes:
      - ../db-data:/var/lib/postgresql/data
      - ../../init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - banking-network
    restart: always

networks:
  banking-network:
    external: true

volumes:
  db_data:
